- name: build binary on all nodes
  hosts: all
  any_errors_fatal: true
  tasks:
  - name: build
    include_tasks:
      file: task/build.yaml

- name: run backend
  hosts: data_nodes
  any_errors_fatal: true
  tasks:
  - name: run backend
    include_tasks:
      file: task/run-backend.yaml

- name: run bdevio
  hosts: client
  any_errors_fatal: true
  tasks:
  - name: run bdevio
    include_tasks:
      file: task/run-bdevio.yaml

- name: cleanup previous processes
  hosts: data_nodes
  any_errors_fatal: true
  tasks:
  - name: run kill script
    include_tasks:
      file: task/cleanup.yaml