- name: make
  hosts: all
  tasks:
  - name: build
    include_tasks:
      file: task/build.yaml
  
- name: gen
  hosts: data_nodes
  tasks:
  - name: gen
    include_tasks:
      file: task/jinja.yaml

- name: run backend
  hosts: data_nodes
  tasks:
  - name: run backend
    include_tasks:
      file: task/run-backend.yaml