- name: do everything related to setup
  hosts: client
  tasks:
  - name: clone the project if the folder doesn't exist
    shell:
      cmd: git clone https://github.com/duzitong/spdk.git
    ignore_errors: true
  - name: run git fetch
    shell:
      cmd: cd spdk && git fetch
  - name: checkout to the target branch and pull
    shell:
      cmd: cd spdk && git checkout {{ lookup('env', 'GIT_BRANCH') }} && git pull