- name: clone the project if the folder doesn't exist
  shell:
    cmd: git clone https://github.com/duzitong/spdk.git
  ignore_errors: true # new-node tasks may need to run multiple times
  when: inventory_hostname in groups['new_nodes']
- name: run git fetch
  shell:
    cmd: git fetch
    chdir: spdk
- name: fail when GIT_BRANCH is not defined
  fail:
    msg: GIT_BRANCH is not defined
  when: not lookup('env', 'GIT_BRANCH')
- name: print GIT_BRANCH
  debug:
    msg: The target branch is {{ lookup('env', 'GIT_BRANCH') }}
- name: checkout to the target branch and pull
  shell: 
    cmd: "{{ item }}"
    chdir: spdk
  with_items: 
  - git checkout {{ lookup('env', 'GIT_BRANCH') }}
  - git pull
  - git submodule update
    # cmd: git checkout {{ lookup('env', 'GIT_BRANCH') }} && git pull
- name: cleanup processes before build
  include_tasks:
    file: cleanup.yaml
- name: run build
  shell:
    cmd: make
    chdir: spdk
- name: apply setup.sh
  shell:
    cmd: HUGEMEM=32768 ./scripts/setup.sh
    chdir: spdk
