- name: run kill script
  shell: 
    cmd: "{{ item }}"
    chdir: spdk
    executable: /bin/bash
  with_items: 
  - ./scripts/kill.sh nvmf_tgt
  - ./scripts/kill.sh bdevio
  - ./scripts/kill.sh bdevperf