- name: run binary
  shell:
    cmd: nohup ./bdevio -c conf-jinja.json -r /var/tmp/spdk2.sock -t 300 2>&1 > bdevio.txt &
    chdir: spdk/test/bdev/bdevio
    executable: /bin/bash
  # register: result
  ignore_errors: true
