- name: run binary
  shell:
    cmd: ./bdevio -c conf-jinja.json -r /var/tmp/spdk2.sock -t 10 2>&1
    chdir: spdk/test/bdev/bdevio
    executable: /bin/bash
  register: result
  ignore_errors: true

- name: print output
  debug:
    var: result.stdout_lines
