- name: cleanup previous processes
  include_tasks:
    file: cleanup.yaml
- name: run binary
  shell:
    cmd: nohup ./build/bin/nvmf_tgt &> log.txt &
    chdir: spdk
    executable: /bin/bash
- name: run rpc script
  shell:
    cmd: ./scripts/rpc.py < rpc.txt
    chdir: spdk