- name: cleanup previous processes
  include_tasks:
    file: cleanup.yaml
- name: run binary
  shell:
    cmd: nohup ./build/bin/nvmf_tgt -r /var/tmp/spdk2.sock -m 0x5 &> log-client.txt &
    chdir: spdk
    executable: /bin/bash
- name: run rpc script
  shell:
    cmd: ./scripts/rpc.py -s /var/tmp/spdk2.sock < rpc-client-jinja.txt
    chdir: spdk